/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from "@aws-amplify/data-schema";
import { configure } from "@aws-amplify/data-schema/internals";
import { secret } from "@aws-amplify/backend";

export const schema = configure({
    database: {
        identifier: "IDjMaA8hpf2urMNoU77How",
        engine: "postgresql",
        connectionUri: secret("SQL_CONNECTION_STRING")
    }
}).schema({
    "events": a.model({
        id: a.integer().required(),
        name: a.string(),
        geom: a.string()
    }).identifier([
        "id"
    ]),
    "notes": a.model({
        id: a.id().required(),
        content: a.string(),
        owner: a.string()
    }).identifier([
        "id"
    ]),
    "spatial_ref_sys": a.model({
        srid: a.integer().required(),
        auth_name: a.string(),
        auth_srid: a.integer(),
        srtext: a.string(),
        proj4text: a.string()
    }).identifier([
        "srid"
    ])
});
